### ISSUE TITLE
Use f-strings

### ISSUE THREAD

**Issue by josmithua** [kurt/Learn-Python#1]
If you're learning Python 3 (which I recommend), try using f-strings instead of `.format` or `%`. They're more clear, not to mention faster.

For example, instead of:

```python
print("{} is eating".format(self.name))
```
try:

```python
print(f"{self.name} is eating")
```

See more here: https://realpython.com/python-f-strings/

Cheers bro!

**Comment by kurt** [comment]
Thanks Joshua!
